const express = require('express');
const router = express.Router();

const LoginController = require('../controller/Login/Login')
const AddressController = require('../controller/AddressMaster/AddressMaster')
const MasterDeviceTypeController = require('../controller/Master/DeviceTypeMaster')
const MasterDeviceGroupController = require('../controller/Master/DeviceGroupMaster')
const MasterDeviceServiceController = require('../controller/Master/DeviceServicesMaster')
const MasterOperatingSystemController = require('../controller/Master/OperatingSystemMaster')
const MasterServiceComplianceController = require('../controller/Master/ServiceComplianceMaster')
const DeviceTaskComplianceController = require('../controller/DeviceTaskCompliance/DeviceComp')
const DevicesTaskesController = require('../controller/DeviceTaskCompliance/DeviceTaskes')
const MasterAgentController = require('../controller/Master/AgentMaster')
const DeviceController = require('../controller/Device/device')
const MasterDeviceTaskControler = require('../controller/Master/DeviceTask')
const SeriesController = require('../controller/Master/SeriesMaster')
const countController = require('../controller/Master/Count')
const OrganizationController = require('../controller/Drizzle/Master/organizationmaster')
const LocationMasterController = require('../controller/Drizzle/Master/locationmaster')
const EmployeeMasterController = require('../controller/Drizzle/Master/employeemaster')
const AssetTypeMasterController = require('../controller/Drizzle/Master/AssetTypeMaster')
const AssetStatusMasterController = require('../controller/Drizzle/Master/AssetStatusMaster')
const ManufacturerMasterController = require('../controller/Drizzle/Master/ManufacturerMaster')
const SoftwareMasterController = require('../controller/Drizzle/Master/SoftwareMaster')
const IssueTypeMasterController = require('../controller/Drizzle/Master/IssueTypeMaster')
const PurchaseTypeMasterController = require('../controller/Drizzle/Master/PurchaseTypeMaster')
const ContractTypeMasterController = require('../controller/Drizzle/Master/ContracttypeMaster')
const PriorityMasterController = require('../controller/Drizzle/Master/PriorityMaster')
const TicketStatusMasterController = require('../controller/Drizzle/Master/TicketStatusMaster')
const BillingFrequencyMasterController = require('../controller/Drizzle/Master/BillingFrequencyMaster')
const VendorCategoryMasterController = require('../controller/Drizzle/Master/VendorCategoryMaster')
const VendorSubCategoryMasterController = require('../controller/Drizzle/Master/VendorSubCategorMaster')
const ServiceActionTypeMaster = require('../controller/Drizzle/Master/ServiceActionTpyeMaster')
const ServiceGroupMasterController = require('../controller/Drizzle/Master/ServiceGroupMaster')
const VendorCodeMasterController = require('../controller/Drizzle/Master/VendorCodeMaster')
const VendorContractMasterController = require('../controller/Drizzle/Master/VendorContractMaster')
const VendorInvoiceController = require('../controller/Drizzle/Main/VendorInvoice')
const NewAssetsController = require('../controller/Drizzle/Main/NewAssets')
const AssetSubController = require('../controller/Drizzle/Main/SubAssets')
const TicketsController = require('../controller/Drizzle/Main/Tickets')
const DashboardController = require('../controller/Dashboard/Dashboard')
const TicketDashboarController = require('../controller/Dashboard/Ticket Dashboard/Ticket')
const VendorDashboardController = require('../controller/Dashboard/Vendor Dashboard/VendorDashboard')
const InvoiceDashboardController = require('../controller/Dashboard/InvoiceDashboard/Invoice')
const OrganisationController = require('../controller/Organisation/organistion')
const UserprofileController = require('../controller/Profile/profile')
const RolesMasterController = require('../controller/Drizzle/Role/RoleMaster')
const ReportMasterController = require('../controller/Report/report')
const MailMasterController = require('../controller/Mail/mail')

const FileUpload = require('../controller/FileUpload/fileupload')
const Multer = require('../Middleware/multer')


router.post('/login',LoginController.UserLogin)
router.post('/ChangePassword',LoginController.ChangePassword)
router.post('/insertuserlogin',LoginController.insertUserLogin)

router.get('/totalcountry',AddressController.totalcountry)
router.post('/totalstate',AddressController.totalstate)
router.post('/totalcity',AddressController.totalcity)


router.get('/totaldevicetypemaster',MasterDeviceTypeController.totaldevicetype)
router.post('/adddevicetypemaster',MasterDeviceTypeController.adddevicetype)
router.post('/getdevicetypemaster',MasterDeviceTypeController.getdevicetype)
router.post('/updatedevicetypemaster',MasterDeviceTypeController.updatedevicetype)
router.post('/updatetypestatusmaster',MasterDeviceTypeController.updatestatus)
router.get('/activedevicetype',MasterDeviceTypeController.Activedevicetype)

router.get('/totaldevicegroupmaster',MasterDeviceGroupController.totaldevicegroup)
router.post('/adddevicegroupmaster',MasterDeviceGroupController.adddevicegroup)
router.post('/getdevicegroupmaster',MasterDeviceGroupController.getdevicegroup)
router.post('/updatedevicegroupmaster',MasterDeviceGroupController.updatedevicegroup)
router.post('/updategroupstatusmaster',MasterDeviceGroupController.updategroupstatus)
router.get('/activedevicegroup', MasterDeviceGroupController.activedevicegroup)

router.get('/totaloperatingsystemmaster',MasterOperatingSystemController.totaloperatingsystem)
router.post('/addoperatingsystemmaster',MasterOperatingSystemController.addoperatingsystemmaster)
router.post('/getoperatingsystemmaster',MasterOperatingSystemController.getoperatingsystem)
router.post('/updateoperatingsystemmaster',MasterOperatingSystemController.updateoperatingsystem)
router.post('/updateoperatingstatusstatusmaster',MasterOperatingSystemController.updateoperatingstatusstatus)
router.get('/activeoperatingsystem',MasterOperatingSystemController.activeoperatingsystem)

router.get('/totaldeviceservicesmaster',MasterDeviceServiceController.totaldeviceservices)
router.post('/adddeviceservicemaster',MasterDeviceServiceController.adddeviceservice)
router.post('/getdeviceservicemaster',MasterDeviceServiceController.getdeviceservice)
router.post('/updatedeviceservicemaster',MasterDeviceServiceController.updatedeviceservice)
router.post('/updatedeviceservicestatusmaster',MasterDeviceServiceController.updatedeviceservicestatus)
router.get('/activedeviceservice',MasterDeviceServiceController.ActiveDeviceService)

router.get('/totalservicecompliancemaster',MasterServiceComplianceController.totalservicecompliance)
router.post('/addservicecompliancemaster',MasterServiceComplianceController.addservicecompliance)
router.post('/getservicecompliancemaster',MasterServiceComplianceController.getservicecompliance)
router.post('/updateservicecompliancemaster',MasterServiceComplianceController.updateservicecompliance)
router.post('/updateservicecompliancestatusmaster',MasterServiceComplianceController.updateservicecompliancestatus)
router.get('/activeservicecompliance',MasterServiceComplianceController.activeservicecompliance)

router.get('/totaldevicetaskcomp',DeviceTaskComplianceController.totaldevicetask)
router.post('/adddeviceTaskcomp',DeviceTaskComplianceController.adddevicetask)
router.post('/getdevicetaskcomp',DeviceTaskComplianceController.getdevicetask)
router.post('/updatedevicetaskcomp',DeviceTaskComplianceController.updatedevicetask)
router.post('/updatedevicecompstatus',DeviceTaskComplianceController.updatedevicecompstatus)
router.post('/getdevicetaskcompliancebyname',DeviceTaskComplianceController.getdevicetaskcompliancebyname)

router.get('/totalagentmaster',MasterAgentController.totalagent)
router.post('/addagentmaster',MasterAgentController.addagent)
router.post('/getagentmaster',MasterAgentController.getagent)
router.post('/updateagentmaster',MasterAgentController.updateagent)
router.post('/updateagentstatusmaster',MasterAgentController.updateagentstatus)
router.get('/activeagent',MasterAgentController.Activeagent)

router.get('/totaldevicetaskmaster',MasterDeviceTaskControler.totaldevicetask)
router.post('/adddevicetaskmaster',MasterDeviceTaskControler.adddevicetask)
router.post('/getdevicetaskmaster',MasterDeviceTaskControler.getdevicetask)
router.post('/updatedevicetaskmaster',MasterDeviceTaskControler.updatedevicetask)
router.post('/updatedevicetaskstatusmaster',MasterDeviceTaskControler.updatestatus)
router.get('/activedevicetask',MasterDeviceTaskControler.Activedevicetask)
router.post('/getdevicetaskfrequency',MasterDeviceTaskControler.getdevicetaskfrequency)

router.get('/totalseries',SeriesController.totalseries)
router.post('/addseries',SeriesController.addseries)
router.post('/getseries',SeriesController.getseries)
router.post('/updateseries',SeriesController.updateseries)
router.post('/updatesseriestatus',SeriesController.updatestatus)
router.get('/activeseriesmaster',SeriesController.Activeseriesmaster)

router.post('/totalcount',countController.totalcount)

router.get('/totaldevice',DeviceController.totaldevice)
router.post('/adddevice',DeviceController.AddDevice)
router.post('/getdevice',DeviceController.getdevice)
router.post('/updatedevice',DeviceController.updatedevice)
router.post('/updatedevicestatus',DeviceController.updatedevicestatus)
router.get('/activedevice',DeviceController.Activedevice)

router.post('/getdevicetaskbyname',DevicesTaskesController.getdevicetaskbyname)
router.post('/adddevicetaskes',DevicesTaskesController.adddevicetaskes)
router.post('/Getdevicestask',DevicesTaskesController.Getdevicetaskes)
router.post('/updatedevicetaskes',DevicesTaskesController.updatedevicetaskes)
router.post('/updatedevicetaskastatus',DevicesTaskesController.updatedevicetaskastatus)

router.post('/totalorganization',OrganizationController.totalOrganization)
router.post('/insertorganization',OrganizationController.insertOrganization)
router.post('/getorganization',OrganizationController.getOrganization)
router.post('/deleteorganization',OrganizationController.deleteOrganization)
router.post('/updateorganization',OrganizationController.updateOrganization)

router.post('/totalLocation',LocationMasterController.totalLocation)
router.post('/insertLocation',LocationMasterController.insertLocation)
router.post('/getLocation',LocationMasterController.getLocation)
router.post('/deleteLocation',LocationMasterController.deleteLocation)
router.post('/updateLocation',LocationMasterController.updateLocation)
router.post('/getalllocation',LocationMasterController.getAllLocation)

router.post('/totalEmployee',EmployeeMasterController.totalEmployee)
router.post('/insertEmployee',EmployeeMasterController.insertEmployee)
router.post('/getEmployee',EmployeeMasterController.getEmployee)
router.post('/deleteEmployee',EmployeeMasterController.deleteEmployee)
router.post('/updateEmployee',EmployeeMasterController.updateEmployee)
router.post('/ActiveEmployee',EmployeeMasterController.ActiveEmployee)
router.post('/EmployeeDetail',EmployeeMasterController.EmployeeDetail)

router.post('/totalAssetType',AssetTypeMasterController.totalAssetType)
router.post('/insertAssetType',AssetTypeMasterController.insertAssetType)
router.post('/getAssetType',AssetTypeMasterController.getAssetType)
router.post('/deleteAssetType',AssetTypeMasterController.deleteAssetType)
router.post('/updateAssetType',AssetTypeMasterController.updateAssetType)
router.post('/ActiveAssetesType',AssetTypeMasterController.ActiveAssetesType)

router.post('/totalAssetStatus',AssetStatusMasterController.totalAssetStatus)
router.post('/insertAssetStatus',AssetStatusMasterController.insertAssetStatus)
router.post('/getAssetStatus',AssetStatusMasterController.getAssetStatus)
router.post('/deleteAssetStatus',AssetStatusMasterController.deleteAssetStatus)
router.post('/updateAssetStatus',AssetStatusMasterController.updateAssetStatus)
router.post('/ActiveAssetesStatus',AssetStatusMasterController.ActiveAssetesStatus)

router.post('/totalManufacturer',ManufacturerMasterController.totalManufacturer)
router.post('/insertManufacturer',ManufacturerMasterController.insertManufacturer)
router.post('/getManufacturer',ManufacturerMasterController.getManufacturer)
router.post('/deleteManufacturer',ManufacturerMasterController.deleteManufacturer)
router.post('/updateManufacturer',ManufacturerMasterController.updateManufacturer)
router.post('/ActiveManufacturer',ManufacturerMasterController.ActiveManufacturer)

router.post('/totalSoftware',SoftwareMasterController.totalSoftware)
router.post('/insertSoftware',SoftwareMasterController.insertSoftware)
router.post('/getSoftware',SoftwareMasterController.getSoftware)
router.post('/deleteSoftware',SoftwareMasterController.deleteSoftware)
router.post('/updateSoftware',SoftwareMasterController.updateSoftware)
router.post('/ActiveSoftware',SoftwareMasterController.ActiveSoftware)

router.post('/totalIssueType',IssueTypeMasterController.totalIssueType)
router.post('/insertIssueType',IssueTypeMasterController.insertIssueType)
router.post('/getIssueType',IssueTypeMasterController.getIssueType)
router.post('/deleteIssueType',IssueTypeMasterController.deleteIssueType)
router.post('/updateIssueType',IssueTypeMasterController.updateIssueType)
router.post('/ActiveIssue',IssueTypeMasterController.ActiveIssue)

router.post('/totalPurchasetype',PurchaseTypeMasterController.totalPurchasetype)
router.post('/insertPurchasetype',PurchaseTypeMasterController.insertPurchasetype)
router.post('/getPurchasetype',PurchaseTypeMasterController.getPurchasetype)
router.post('/deletePurchasetype',PurchaseTypeMasterController.deletePurchasetype)
router.post('/updatePurchasetype',PurchaseTypeMasterController.updatePurchasetype)
router.post('/ActivePurchasetype',PurchaseTypeMasterController.ActivePurchasetype)

router.post('/totalContracttype',ContractTypeMasterController.totalContracttype)
router.post('/insertContracttype',ContractTypeMasterController.insertContracttype)
router.post('/getContracttype',ContractTypeMasterController.getContracttype)
router.post('/deleteContracttype',ContractTypeMasterController.deleteContracttype)
router.post('/updateContracttype',ContractTypeMasterController.updateContracttype)
router.post('/getallcontracttype',ContractTypeMasterController.getAllContracttype)

router.post('/totalPriority',PriorityMasterController.totalPriorityMaster)
router.post('/insertPriority',PriorityMasterController.insertPriorityMaster)
router.post('/getPriority',PriorityMasterController.getPriorityMaster)
router.post('/deletePriority',PriorityMasterController.deletePriorityMaster)
router.post('/updatePriority',PriorityMasterController.updatePriorityMaster)
router.post('/ActivePriority',PriorityMasterController.ActivePriority)

router.post('/totalTicketStatus',TicketStatusMasterController.totalTicketStatus)
router.post('/insertTicketStatus',TicketStatusMasterController.insertTicketStatus)
router.post('/getTicketStatus',TicketStatusMasterController.getTicketStatus)
router.post('/deleteTicketStatus',TicketStatusMasterController.deleteTicketStatus)
router.post('/updateTicketStatus',TicketStatusMasterController.updateTicketStatus)
router.post('/ActiveTicketStatus',TicketStatusMasterController.ActiveTicketStatus)

router.post('/totalBillingFrequency',BillingFrequencyMasterController.totalBillingFrequency)
router.post('/insertBillingFrequency',BillingFrequencyMasterController.insertBillingFrequency)
router.post('/getBillingFrequency',BillingFrequencyMasterController.getBillingFrequency)
router.post('/deleteBillingFrequency',BillingFrequencyMasterController.deleteBillingFrequency)
router.post('/updateBillingFrequency',BillingFrequencyMasterController.updateBillingFrequency)
router.post('/ActiveBillingFreq',BillingFrequencyMasterController.ActiveBillingFreq)

router.post('/totalVendorCategory',VendorCategoryMasterController.totalVendorCategory)
router.post('/insertVendorCategory',VendorCategoryMasterController.insertVendorCategory)
router.post('/getVendorCategory',VendorCategoryMasterController.getVendorCategory)
router.post('/deleteVendorCategory',VendorCategoryMasterController.deleteVendorCategory)
router.post('/updateVendorCategory',VendorCategoryMasterController.updateVendorCategory)
router.post('/getallvendorcategory',VendorCategoryMasterController.getAllVendorCategory)

router.post('/totalVendorSubCategory',VendorSubCategoryMasterController.totalVendorSubCategory)
router.post('/insertVendorSubCategory',VendorSubCategoryMasterController.insertVendorSubCategory)
router.post('/getVendorSubCategory',VendorSubCategoryMasterController.getVendorSubCategory)
router.post('/deleteVendorSubCategory',VendorSubCategoryMasterController.deleteVendorSubCategory)
router.post('/updateVendorSubCategory',VendorSubCategoryMasterController.updateVendorSubCategory)
router.post('/getvendorsubcategorybyvend',VendorSubCategoryMasterController.getVendorSubCategoryby)

router.post('/totalServiceAction',ServiceActionTypeMaster.totalServiceAction)
router.post('/insertServiceAction',ServiceActionTypeMaster.insertServiceAction)
router.post('/getServiceAction',ServiceActionTypeMaster.getServiceAction)
router.post('/deleteServiceAction',ServiceActionTypeMaster.deleteServiceAction)
router.post('/updateServiceAction',ServiceActionTypeMaster.updateServiceAction)

router.post('/totalServiceGroup',ServiceGroupMasterController.totalServiceGroup)
router.post('/insertServiceGroup',ServiceGroupMasterController.insertServiceGroup)
router.post('/getServiceGroup',ServiceGroupMasterController.getServiceGroup)
router.post('/deleteServiceGroup',ServiceGroupMasterController.deleteServiceGroup)
router.post('/updateServiceGroup',ServiceGroupMasterController.updateServiceGroup)

router.post('/totalVendorCode',VendorCodeMasterController.totalVendorCode)
router.post('/insertVendorCode',VendorCodeMasterController.insertVendorCode)
router.post('/getVendorCode',VendorCodeMasterController.getVendorCode)
router.post('/deleteVendorCode',VendorCodeMasterController.deleteVendorCode)
router.post('/updateVendorCode',VendorCodeMasterController.updateVendorCode)
router.post('/getallvendor',VendorCodeMasterController.GetAllVendor)
router.post('/getvendordetails',VendorCodeMasterController.GetVendorDetails)

router.post('/totalVendorContract',VendorContractMasterController.totalVendorContract)
router.post('/insertVendorContract',VendorContractMasterController.insertVendorContract)
router.post('/getVendorContract',VendorContractMasterController.getVendorContract)
router.post('/deleteVendorContract',VendorContractMasterController.deleteVendorContract)
router.post('/updateVendorContract',VendorContractMasterController.updateVendorContract)
router.post('/ActiveVendorContract',VendorContractMasterController.ActiveVendorContract)
router.post('/VendorContractDetail',VendorContractMasterController.VendorContractDetail)
router.post('/vendorcontractonchange',VendorContractMasterController.VendorContractonChange)


router.post('/InsertVendorInvoice',VendorInvoiceController.InsertVendorInvoice)
router.post('/PendingVendorInvoice',VendorInvoiceController.PendingVendorInvoice)
router.post('/GetVendorInvoice',VendorInvoiceController.GetVendorInvoice)
router.post('/UpdatePendingVendorInvoice',VendorInvoiceController.UpdatePendingVendorInvoice)
router.post('/UpdateVendorInvoice',VendorInvoiceController.UpdateVendorInvoice)
router.post('/TotalVendorPayment',VendorInvoiceController.TotalVendorPayment)
router.post('/GetVendorPayment',VendorInvoiceController.GetVendorPayment)
router.post('/UpdateVendorPayment',VendorInvoiceController.UpdateVendorPayment)
router.post('/UploadInvoice',VendorInvoiceController.UploadDocument)
router.post('/vendorinvoiceonchange',VendorInvoiceController.VendorInvoiceonChange)


router.post('/TotalNewAssets',NewAssetsController.TotalNewAssets)
router.post('/InsertNewAssets',NewAssetsController.InsertNewAssets)
router.post('/DeleteNewAssets',NewAssetsController.DeleteNewAssets)
router.post('/GetNewAssets',NewAssetsController.GetNewAssets)
router.post('/CountNewAssets',NewAssetsController.CountNewAssets)
router.post('/GetNewAssetAssign',NewAssetsController.GetNewAssetAssign)
router.post('/UpdateNewAssets',NewAssetsController.UpdateNewAssets)

router.post('/insertassetssoftware',AssetSubController.InsertAssetsSoftware)
router.post('/getnewassetssoftware',AssetSubController.GetNewAssetsSoftware)

router.post('/InsertTicket',TicketsController.InsertTicket)
router.post('/CountTickets',TicketsController.CountTickets)
router.post('/TotalTicket',TicketsController.TotalTicket)
router.post('/DeleteTickets',TicketsController.DeleteTickets)
router.post('/getTickets',TicketsController.getTickets)
router.post('/UpdateTicket',TicketsController.UpdateTicket)
router.post('/OpenTotalTicket',TicketsController.OpenTotalTicket)
router.post('/TotalHoldTicket',TicketsController.TotalHoldTicket)


router.post('/dashboard_details',DashboardController.dashboard_details)
router.post('/dashboard_procedure',DashboardController.dashboard_procedure)
router.post('/dashboard_location_name',DashboardController.dashboard_location_name)
router.post('/dashboard_software',DashboardController.dashboard_software)
router.post('/dashboard_manufacture',DashboardController.dashboard_manufacture)
router.post('/dashboard_asset_data',DashboardController.dashboard_asset_data)

router.post('/ticket_summary',TicketDashboarController.Ticket_Summary)
router.post('/ticket_priority',TicketDashboarController.Ticket_Priority)
router.post('/ticket_issue_type',TicketDashboarController.Ticket_issue_type)
router.post('/filter_ticket_summary',TicketDashboarController.Filter_Ticket_Summary)
router.post('/filter_ticket_summary_count',TicketDashboarController.Filter_Ticket_Summary_Count)



router.post('/ReferanceNumber',VendorDashboardController.ReferanceNumber)
router.post('/RecurringVendor',VendorDashboardController.RecurringVendor)
router.post('/RecurringFrequency',VendorDashboardController.RecurringFrequency)
router.post('/TotalVendorContractDetails',VendorDashboardController.TotalVendorContract)
router.post('/FilterVendorContract',VendorDashboardController.FilterVendorContract)
router.post('/exporttotalvendorcontract',VendorDashboardController.ExportTotalVendorContract)

router.post('/Invoice_Outstanding',InvoiceDashboardController.Invoice_Outstanding)
router.post('/TotalOutstanding',InvoiceDashboardController.TotalOutstanding)
router.post('/VendorInvoice',InvoiceDashboardController.VendorInvoice)
router.post('/PaidInvoice',InvoiceDashboardController.PaidInvoice)
router.post('/FilterInvoice',InvoiceDashboardController.FilterInvoice)
router.post('/recurringpendinginvoice',InvoiceDashboardController.Recurring_Pending_Invoice)
router.post('/outstandinginvoicefilter',InvoiceDashboardController.Outstanding_Invoice_filter)
router.post('/exportoutstandinginvoicedata',InvoiceDashboardController.ExportOutstandingInvoiceData)

router.post('/getuserdetails',UserprofileController.getUserdetails)
router.post('/updateuserdetails',UserprofileController.updateUserdetails)

router.post('/addorganisation',OrganisationController.AddOrganisation)
router.post('/getorganisation',OrganisationController.getOrganisation)
router.post('/updateorganizationdetails',OrganisationController.updateOrganizationDetails)

router.post('/totalroles',RolesMasterController.totalRoles)
router.post('/insertroles',RolesMasterController.insertRoles)
router.post('/getrole',RolesMasterController.getRole)
router.post('/updaterole',RolesMasterController.updateRole)

router.post('/FileUpload',Multer,FileUpload)

router.post('/ColumnsReport',ReportMasterController.ColumnsReport)
router.post('/tableReports',ReportMasterController.TableReports)
router.post('/GraphReport',ReportMasterController.GraphReport)
router.post('/assetreport',ReportMasterController.AssetReport)

router.post('/Email',MailMasterController.Email)
router.post('/assetemail',MailMasterController.AssetEmail)
router.post('/invoiceemail',MailMasterController.InvoiceEmail)
router.post('/vendorpaymentemail',MailMasterController.VendorPaymentEmail)
router.post('/vendorcreateemail',MailMasterController.VendorCreateEmail)
router.post('/employeecreateemail',MailMasterController.EmployeeCreateEmail)
router.post('/vendorcontractemail',MailMasterController.VendorContractEmail)




module.exports = router
